main: church_numerals_chibiscm

# chibi-scheme
y_comb_chibiscm:
	chibi-scheme y_comb.chibi.scm
church_numerals_chibiscm:
	chibi-scheme church_numerals.chibi.scm

# mit-scheme

bscm:
	mit-scheme --quiet --load b.scm --eval '(exit)'
cscm:
	mit-scheme --quiet --load c.scm --eval '(exit)'
