spring:
  application:
    name: spring-authorization-server-demo
  datasource:
    url: jdbc:h2:mem:authdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: INFO

server:
  port: 8081
