exec: algocc
		cat 0 | ./a.exe

algocl: 
		gcc ./algo.c -std=c99

algogo:
		cat 0 | go run ./algo.go
algocpp_seam:
	g++ -o a.exe ./sema.cpp -Wall -std=c++20

algocc:
	 g++ -o a.exe ./algo.cc -Wall -std=c++20
	
algojava:
	javac Algo.java && java Algo.class
	
fibanocci_heap:
	gcc ./fibanocci_heap.c -std=c99


run: keyrecorder
	cat 0 | ./app.exe
	
keyrecorder:
	g++ -oapp -m64 keyrecorder.cpp









pixel:
	g++ -opixel -I C:///Users/zqshe/olcPixelGameEngine/  pixel.cpp







geometry:
	g++ -ogeometry -I C:///Users/zqshe/olcUTIL_Geometry2D/ geometry.cpp


binary_indexed_tree:
	gcc ./binary_indexed_tree.c


clean:
	rm a.exe


